name: Install Packages with Pip
description: A fully-featured `pip install` wrapper for GitHub Actions.
author: Ethan Henderson
branding:
  icon: 'download'
  color: 'blue'
inputs:
  packages:
    description: The packages to install.
    required: false
    default: ''
  requirement:
    description: Install from the given requirements file. Multiple files can be provided.
    required: false
    default: ''
  constraint:
    description: Constrain versions using the given constraints file. Multiple files can be provided.
    required: false
    default: ''
  no-deps:
    description: Don't install package dependencies.
    required: false
    default: 'false'
  pre:
    description: Include pre-release and development versions. By default, pip only finds stable versions.
    required: false
    default: 'false'
  editable:
    description: Install a project in editable mode (i.e. setuptools "develop mode") from a local project path or a VCS url.
    required: false
    default: ''
runs:
  using: node16
  main: dist/index.js
